steps:
- task: Bash@3
  displayName: Download packer
  inputs:
    targetType: 'inline'
    script: |
      mkdir -p ~/.local/bin
      curl -s https://releases.hashicorp.com/packer/${{ parameters.packer_version}}/packer_${{ parameters.packer_version}}_linux_amd64.zip --output packer.zip
      unzip packer.zip
      mv packer ~/.local/bin/
      ##vso[task.prependpath]~/.local/bin
    workingDirectory: '/tmp'
    failOnStandardError: true

- task: AzureCLI@2
  displayName: Prepare environment variables
  inputs:
    azureSubscription: ${{ parameters.service_connection }}
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: |
      echo "##vso[task.setvariable variable=ARM_CLIENT_ID]$servicePrincipalId"
      echo "##vso[task.setvariable variable=ARM_CLIENT_SECRET;issecret=true]$servicePrincipalKey"
      echo "##vso[task.setvariable variable=ARM_TENANT_ID]$tenantId"
      echo "##vso[task.setvariable variable=ARM_SUBSCRIPTION_ID]$(az account show| jq -r '.id')"
      echo "##vso[task.setvariable variable=AGENT_IP]$(curl -s http://ipinfo.io/json| jq -r '.ip')"
    addSpnToEnvironment: true
    failOnStandardError: true
