trigger: none
pr: none

resources:
  repositories:
  - repository: virtual-environments-github
    name: actions/virtual-environments
    type: github
    endpoint: <name of github service connection>
    trigger:
      branches:
        include:
        - refs/heads/win16/*

jobs:
- job: image_generation_windows2016
  displayName: Image Generation (windows2016)
  timeoutInMinutes: 360 # 6 hours
  pool:
    vmImage: ubuntu-latest
  steps:
  - checkout: self
    path: self

  - checkout: virtual-environments-github
    path: virtual-environments

  - template: templates/packer-prep.yml
    parameters:
      service_connection: <name of azure service connection>
      packer_version: 1.7.8

  - task: Bash@3
    displayName: Generate temporary vm password
    inputs:
      targetType: 'inline'
      script: |
        temporary_packer_password=$(date +%s | sha256sum | base64 | head -c 32 ; echo)
        echo "##vso[task.setvariable variable=TMP_PACKER_PASSWORD;issecret=true]$temporary_packer_password"
      failOnStderr: true

  - template: templates/build_image.yml
    parameters:
      image_detinition_path: images/win
      image_definition_file: windows2016.json
      vars:
        install_password: $(TMP_PACKER_PASSWORD)
      env:
        ARM_CLIENT_ID: $(ARM_CLIENT_ID)
        ARM_CLIENT_SECRET: $(ARM_CLIENT_SECRET)
        ARM_TENANT_ID: $(ARM_TENANT_ID)
        ARM_SUBSCRIPTION_ID: $(ARM_SUBSCRIPTION_ID)
        AGENT_IP: $(AGENT_IP)
        ARM_RESOURCE_LOCATION: northeurope
        ARM_RESOURCE_GROUP: <resource group name of storage for VHD>
        ARM_STORAGE_ACCOUNT: <storage account name to store VHD artifacts>
